trigger:
- master

variables:
  # Azure service connection established during pipeline creation
  azureSubscription: 'da41eab6-8818-4865-a2e7-4aef0be9d6c0'
  appName: 'azureTest-purinit'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
- task: AzureWebApp@1 # Add this at the end of your file
  inputs:
    azureSubscription: $(azureSubscription)
    appType: webAppLinux
    appName: $(appName)
    package: $(System.ArtifactsDirectory)/**/*.war